// Danh mục mã ngành VSIC 2018 — top phổ biến (rút gọn).
// Người dùng có thể nhập mã tay nếu không có trong danh sách.
export const VSIC: { code: string; name: string }[] = [
  { code: "4610", name: "Đại lý, môi giới, đấu giá hàng hóa" },
  { code: "4631", name: "Bán buôn thực phẩm" },
  { code: "4632", name: "Bán buôn đồ uống" },
  { code: "4641", name: "Bán buôn vải, hàng may sẵn, giày dép" },
  { code: "4649", name: "Bán buôn đồ dùng khác cho gia đình" },
  { code: "4651", name: "Bán buôn máy vi tính, thiết bị ngoại vi và phần mềm" },
  { code: "4652", name: "Bán buôn thiết bị, linh kiện điện tử, viễn thông" },
  { code: "4659", name: "Bán buôn máy móc, thiết bị khác" },
  { code: "4663", name: "Bán buôn vật liệu, thiết bị lắp đặt khác trong xây dựng" },
  { code: "4711", name: "Bán lẻ lương thực, thực phẩm tổng hợp" },
  { code: "4719", name: "Bán lẻ khác trong các cửa hàng tổng hợp" },
  { code: "4741", name: "Bán lẻ máy vi tính, thiết bị ngoại vi, phần mềm" },
  { code: "4752", name: "Bán lẻ đồ ngũ kim, sơn, kính" },
  { code: "4761", name: "Bán lẻ sách, báo, văn phòng phẩm" },
  { code: "4933", name: "Vận tải hàng hóa bằng đường bộ" },
  { code: "5210", name: "Kho bãi và lưu giữ hàng hóa" },
  { code: "5224", name: "Bốc xếp hàng hóa" },
  { code: "5320", name: "Chuyển phát" },
  { code: "5510", name: "Dịch vụ lưu trú ngắn ngày" },
  { code: "5610", name: "Nhà hàng và các dịch vụ ăn uống phục vụ lưu động" },
  { code: "5621", name: "Cung cấp dịch vụ ăn uống theo hợp đồng không thường xuyên" },
  { code: "5811", name: "Xuất bản sách" },
  { code: "5820", name: "Xuất bản phần mềm" },
  { code: "6201", name: "Lập trình máy vi tính" },
  { code: "6202", name: "Tư vấn máy vi tính và quản trị hệ thống máy vi tính" },
  { code: "6209", name: "Hoạt động dịch vụ công nghệ thông tin và dịch vụ khác liên quan đến máy vi tính" },
  { code: "6311", name: "Xử lý dữ liệu, cho thuê và các hoạt động liên quan" },
  { code: "6312", name: "Cổng thông tin" },
  { code: "6411", name: "Hoạt động ngân hàng trung ương" },
  { code: "6491", name: "Cho thuê tài chính" },
  { code: "6492", name: "Hoạt động cấp tín dụng khác" },
  { code: "6810", name: "Kinh doanh bất động sản, quyền sử dụng đất thuộc chủ sở hữu, chủ sử dụng hoặc đi thuê" },
  { code: "6820", name: "Tư vấn, môi giới, đấu giá bất động sản, đấu giá quyền sử dụng đất" },
  { code: "6920", name: "Hoạt động liên quan đến kế toán, kiểm toán và tư vấn về thuế" },
  { code: "7020", name: "Hoạt động tư vấn quản lý" },
  { code: "7110", name: "Hoạt động kiến trúc và tư vấn kỹ thuật có liên quan" },
  { code: "7210", name: "Nghiên cứu và phát triển thực nghiệm khoa học tự nhiên và kỹ thuật" },
  { code: "7310", name: "Quảng cáo" },
  { code: "7320", name: "Nghiên cứu thị trường và thăm dò dư luận" },
  { code: "7410", name: "Hoạt động thiết kế chuyên dụng" },
  { code: "7710", name: "Cho thuê xe có động cơ" },
  { code: "7820", name: "Cung ứng lao động tạm thời" },
  { code: "7911", name: "Đại lý du lịch" },
  { code: "8211", name: "Dịch vụ hành chính văn phòng tổng hợp" },
  { code: "8230", name: "Tổ chức giới thiệu và xúc tiến thương mại" },
  { code: "8299", name: "Hoạt động dịch vụ hỗ trợ kinh doanh khác còn lại chưa được phân vào đâu" },
  { code: "8510", name: "Giáo dục mầm non" },
  { code: "8559", name: "Giáo dục khác chưa được phân vào đâu" },
  { code: "8621", name: "Hoạt động y tế dự phòng" },
  { code: "9511", name: "Sửa chữa máy vi tính và thiết bị ngoại vi" },
  { code: "9609", name: "Hoạt động dịch vụ phục vụ cá nhân khác còn lại chưa được phân vào đâu" },
];

export const LEGAL_FORMS: { value: string; label: string }[] = [
  { value: "llc", label: "Công ty TNHH" },
  { value: "jsc", label: "Công ty Cổ phần" },
  { value: "partnership", label: "Công ty Hợp danh" },
  { value: "sole_prop", label: "Doanh nghiệp tư nhân" },
  { value: "household", label: "Hộ kinh doanh" },
  { value: "branch", label: "Chi nhánh / VPĐD" },
  { value: "other", label: "Khác" },
];

export const TAX_METHODS: { value: string; label: string }[] = [
  { value: "deduction", label: "Khấu trừ" },
  { value: "direct_revenue", label: "Trực tiếp trên doanh thu" },
  { value: "direct_gtgt", label: "Trực tiếp trên GTGT" },
];

export const DECLARE_PERIODS: { value: string; label: string }[] = [
  { value: "monthly", label: "Kê khai theo tháng" },
  { value: "quarterly", label: "Kê khai theo quý" },
];
