// Vietnamese Accounting Standards — common account codes for display.
export const VAS_ACCOUNTS: Record<string, string> = {
  "111": "Tiền mặt",
  "112": "Tiền gửi ngân hàng",
  "131": "Phải thu khách hàng",
  "133": "Thuế GTGT được khấu trừ",
  "138": "Phải thu khác",
  "141": "Tạm ứng",
  "152": "Nguyên vật liệu",
  "153": "Công cụ dụng cụ",
  "154": "CP SXKD dở dang",
  "155": "Thành phẩm",
  "156": "Hàng hóa",
  "211": "TSCĐ hữu hình",
  "213": "TSCĐ vô hình",
  "214": "Hao mòn TSCĐ",
  "242": "Chi phí trả trước",
  "311": "Vay ngắn hạn",
  "331": "Phải trả người bán",
  "333": "Thuế và các khoản phải nộp NN",
  "334": "Phải trả người lao động",
  "335": "Chi phí phải trả",
  "338": "Phải trả phải nộp khác",
  "341": "Vay dài hạn",
  "411": "Vốn góp chủ sở hữu",
  "421": "LNST chưa phân phối",
  "511": "Doanh thu bán hàng",
  "515": "Doanh thu hoạt động tài chính",
  "521": "Chiết khấu thương mại",
  "611": "Mua hàng",
  "621": "CP NVL trực tiếp",
  "622": "CP nhân công trực tiếp",
  "627": "Chi phí SXC",
  "632": "Giá vốn hàng bán",
  "635": "Chi phí tài chính",
  "641": "Chi phí bán hàng",
  "642": "Chi phí QLDN",
  "711": "Thu nhập khác",
  "811": "Chi phí khác",
  "821": "Chi phí thuế TNDN",
  "911": "Xác định KQKD",
};

export function accountName(code: string): string {
  return VAS_ACCOUNTS[code] ?? `TK ${code}`;
}
