/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppSuperadminRouteImport } from './routes/_app/superadmin'
import { Route as AppSetupRouteImport } from './routes/_app/setup'
import { Route as AppJournalRouteImport } from './routes/_app/journal'
import { Route as AppItemsRouteImport } from './routes/_app/items'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppBankRouteImport } from './routes/_app/bank'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppTaxIndexRouteImport } from './routes/_app/tax/index'
import { Route as AppSuppliersIndexRouteImport } from './routes/_app/suppliers/index'
import { Route as AppSuperadminIndexRouteImport } from './routes/_app/superadmin/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSalesIndexRouteImport } from './routes/_app/sales/index'
import { Route as AppSalesDashboardIndexRouteImport } from './routes/_app/sales-dashboard/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppReceivablesIndexRouteImport } from './routes/_app/receivables/index'
import { Route as AppReceiptsIndexRouteImport } from './routes/_app/receipts/index'
import { Route as AppPurchasesIndexRouteImport } from './routes/_app/purchases/index'
import { Route as AppPayrollIndexRouteImport } from './routes/_app/payroll/index'
import { Route as AppPayablesIndexRouteImport } from './routes/_app/payables/index'
import { Route as AppItemsIndexRouteImport } from './routes/_app/items/index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppEinvoicesIndexRouteImport } from './routes/_app/einvoices/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app/documents/index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppCoaIndexRouteImport } from './routes/_app/coa/index'
import { Route as AppCashIndexRouteImport } from './routes/_app/cash/index'
import { Route as AppBankIndexRouteImport } from './routes/_app/bank.index'
import { Route as AppAssetsIndexRouteImport } from './routes/_app/assets/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppTaxTndnRouteImport } from './routes/_app/tax/tndn'
import { Route as AppTaxTncnRouteImport } from './routes/_app/tax/tncn'
import { Route as AppTaxGtgtRouteImport } from './routes/_app/tax/gtgt'
import { Route as AppSuppliersGroupsRouteImport } from './routes/_app/suppliers/groups'
import { Route as AppSuppliersIdRouteImport } from './routes/_app/suppliers/$id'
import { Route as AppSuperadminOrganizationsRouteImport } from './routes/_app/superadmin/organizations'
import { Route as AppSuperadminAuditRouteImport } from './routes/_app/superadmin/audit'
import { Route as AppSuperadminAccountsRouteImport } from './routes/_app/superadmin/accounts'
import { Route as AppSettingsProjectsRouteImport } from './routes/_app/settings/projects'
import { Route as AppSettingsFiscalPeriodsRouteImport } from './routes/_app/settings/fiscal-periods'
import { Route as AppSettingsDepartmentsRouteImport } from './routes/_app/settings/departments'
import { Route as AppSettingsCostCentersRouteImport } from './routes/_app/settings/cost-centers'
import { Route as AppSettingsBranchesRouteImport } from './routes/_app/settings/branches'
import { Route as AppSalesOrdersRouteImport } from './routes/_app/sales/orders'
import { Route as AppSalesIdRouteImport } from './routes/_app/sales/$id'
import { Route as AppReportsVoucherListRouteImport } from './routes/_app/reports/voucher-list'
import { Route as AppReportsTrialBalanceRouteImport } from './routes/_app/reports/trial-balance'
import { Route as AppReportsStockIosRouteImport } from './routes/_app/reports/stock-ios'
import { Route as AppReportsLedgersRouteImport } from './routes/_app/reports/ledgers'
import { Route as AppReportsArSummaryRouteImport } from './routes/_app/reports/ar-summary'
import { Route as AppReportsApSummaryRouteImport } from './routes/_app/reports/ap-summary'
import { Route as AppReportsAllocationScheduleRouteImport } from './routes/_app/reports/allocation-schedule'
import { Route as AppPayrollIdRouteImport } from './routes/_app/payroll/$id'
import { Route as AppItemsUnitsRouteImport } from './routes/_app/items/units'
import { Route as AppItemsCategoriesRouteImport } from './routes/_app/items/categories'
import { Route as AppInvoicesIdRouteImport } from './routes/_app/invoices/$id'
import { Route as AppInventoryWarehousesRouteImport } from './routes/_app/inventory/warehouses'
import { Route as AppInventoryVouchersOutRouteImport } from './routes/_app/inventory/vouchers-out'
import { Route as AppInventoryVouchersInRouteImport } from './routes/_app/inventory/vouchers-in'
import { Route as AppInventoryStockTakesRouteImport } from './routes/_app/inventory/stock-takes'
import { Route as AppInventoryStockCardRouteImport } from './routes/_app/inventory/stock-card'
import { Route as AppInventoryMovementsRouteImport } from './routes/_app/inventory/movements'
import { Route as AppInventoryIdRouteImport } from './routes/_app/inventory/$id'
import { Route as AppEinvoicesCredentialsRouteImport } from './routes/_app/einvoices/credentials'
import { Route as AppEinvoicesIdRouteImport } from './routes/_app/einvoices/$id'
import { Route as AppCustomersGroupsRouteImport } from './routes/_app/customers/groups'
import { Route as AppBankVouchersRouteImport } from './routes/_app/bank.vouchers'
import { Route as AppBankBookRouteImport } from './routes/_app/bank.book'
import { Route as AppBankAccountsRouteImport } from './routes/_app/bank.accounts'
import { Route as AppAssetsReportsRouteImport } from './routes/_app/assets/reports'
import { Route as AppAssetsReclassifyRouteImport } from './routes/_app/assets/reclassify'
import { Route as AppAssetsInventoryRouteImport } from './routes/_app/assets/inventory'
import { Route as AppAssetsFromInvoiceRouteImport } from './routes/_app/assets/from-invoice'
import { Route as AppAssetsFromFixedAssetRouteImport } from './routes/_app/assets/from-fixed-asset'
import { Route as AppAssetsEventsRouteImport } from './routes/_app/assets/events'
import { Route as AppAssetsDisposalRouteImport } from './routes/_app/assets/disposal'
import { Route as AppAssetsDepreciationRouteImport } from './routes/_app/assets/depreciation'
import { Route as AppAssetsCategoriesRouteImport } from './routes/_app/assets/categories'
import { Route as AppAssetsBooksRouteImport } from './routes/_app/assets/books'
import { Route as AppAssetsAllocationsRouteImport } from './routes/_app/assets/allocations'
import { Route as AppAdminPeriodsRouteImport } from './routes/_app/admin/periods'
import { Route as AppAdminMembersRouteImport } from './routes/_app/admin/members'
import { Route as AppAdminBackupRouteImport } from './routes/_app/admin/backup'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppSuperadminTenantIdRouteImport } from './routes/_app/superadmin/tenant.$id'
import { Route as AppAssetsInventoryIdRouteImport } from './routes/_app/assets/inventory.$id'
import { Route as AppAssetsAllocationsIdRouteImport } from './routes/_app/assets/allocations.$id'
import { Route as AppAssetsIdCardRouteImport } from './routes/_app/assets/$id.card'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuperadminRoute = AppSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsRoute = AppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxIndexRoute = AppTaxIndexRouteImport.update({
  id: '/tax/',
  path: '/tax/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperadminIndexRoute = AppSuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSuperadminRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesDashboardIndexRoute = AppSalesDashboardIndexRouteImport.update({
  id: '/sales-dashboard/',
  path: '/sales-dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivablesIndexRoute = AppReceivablesIndexRouteImport.update({
  id: '/receivables/',
  path: '/receivables/',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsIndexRoute = AppReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesIndexRoute = AppPurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollIndexRoute = AppPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayablesIndexRoute = AppPayablesIndexRouteImport.update({
  id: '/payables/',
  path: '/payables/',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsIndexRoute = AppItemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppItemsRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppEinvoicesIndexRoute = AppEinvoicesIndexRouteImport.update({
  id: '/einvoices/',
  path: '/einvoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoaIndexRoute = AppCoaIndexRouteImport.update({
  id: '/coa/',
  path: '/coa/',
  getParentRoute: () => AppRoute,
} as any)
const AppCashIndexRoute = AppCashIndexRouteImport.update({
  id: '/cash/',
  path: '/cash/',
  getParentRoute: () => AppRoute,
} as any)
const AppBankIndexRoute = AppBankIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBankRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppTaxTndnRoute = AppTaxTndnRouteImport.update({
  id: '/tax/tndn',
  path: '/tax/tndn',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxTncnRoute = AppTaxTncnRouteImport.update({
  id: '/tax/tncn',
  path: '/tax/tncn',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxGtgtRoute = AppTaxGtgtRouteImport.update({
  id: '/tax/gtgt',
  path: '/tax/gtgt',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersGroupsRoute = AppSuppliersGroupsRouteImport.update({
  id: '/suppliers/groups',
  path: '/suppliers/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIdRoute = AppSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSuperadminOrganizationsRoute =
  AppSuperadminOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AppSuperadminRoute,
  } as any)
const AppSuperadminAuditRoute = AppSuperadminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppSuperadminRoute,
} as any)
const AppSuperadminAccountsRoute = AppSuperadminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppSuperadminRoute,
} as any)
const AppSettingsProjectsRoute = AppSettingsProjectsRouteImport.update({
  id: '/settings/projects',
  path: '/settings/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsFiscalPeriodsRoute =
  AppSettingsFiscalPeriodsRouteImport.update({
    id: '/settings/fiscal-periods',
    path: '/settings/fiscal-periods',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsDepartmentsRoute = AppSettingsDepartmentsRouteImport.update({
  id: '/settings/departments',
  path: '/settings/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCostCentersRoute = AppSettingsCostCentersRouteImport.update({
  id: '/settings/cost-centers',
  path: '/settings/cost-centers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBranchesRoute = AppSettingsBranchesRouteImport.update({
  id: '/settings/branches',
  path: '/settings/branches',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersRoute = AppSalesOrdersRouteImport.update({
  id: '/sales/orders',
  path: '/sales/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIdRoute = AppSalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsVoucherListRoute = AppReportsVoucherListRouteImport.update({
  id: '/reports/voucher-list',
  path: '/reports/voucher-list',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsTrialBalanceRoute = AppReportsTrialBalanceRouteImport.update({
  id: '/reports/trial-balance',
  path: '/reports/trial-balance',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsStockIosRoute = AppReportsStockIosRouteImport.update({
  id: '/reports/stock-ios',
  path: '/reports/stock-ios',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsLedgersRoute = AppReportsLedgersRouteImport.update({
  id: '/reports/ledgers',
  path: '/reports/ledgers',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsArSummaryRoute = AppReportsArSummaryRouteImport.update({
  id: '/reports/ar-summary',
  path: '/reports/ar-summary',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsApSummaryRoute = AppReportsApSummaryRouteImport.update({
  id: '/reports/ap-summary',
  path: '/reports/ap-summary',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsAllocationScheduleRoute =
  AppReportsAllocationScheduleRouteImport.update({
    id: '/reports/allocation-schedule',
    path: '/reports/allocation-schedule',
    getParentRoute: () => AppRoute,
  } as any)
const AppPayrollIdRoute = AppPayrollIdRouteImport.update({
  id: '/payroll/$id',
  path: '/payroll/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsUnitsRoute = AppItemsUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppItemsRoute,
} as any)
const AppItemsCategoriesRoute = AppItemsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppItemsRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryWarehousesRoute = AppInventoryWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryVouchersOutRoute = AppInventoryVouchersOutRouteImport.update({
  id: '/vouchers-out',
  path: '/vouchers-out',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryVouchersInRoute = AppInventoryVouchersInRouteImport.update({
  id: '/vouchers-in',
  path: '/vouchers-in',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryStockTakesRoute = AppInventoryStockTakesRouteImport.update({
  id: '/stock-takes',
  path: '/stock-takes',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryStockCardRoute = AppInventoryStockCardRouteImport.update({
  id: '/stock-card',
  path: '/stock-card',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryMovementsRoute = AppInventoryMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryIdRoute = AppInventoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppEinvoicesCredentialsRoute = AppEinvoicesCredentialsRouteImport.update({
  id: '/einvoices/credentials',
  path: '/einvoices/credentials',
  getParentRoute: () => AppRoute,
} as any)
const AppEinvoicesIdRoute = AppEinvoicesIdRouteImport.update({
  id: '/einvoices/$id',
  path: '/einvoices/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersGroupsRoute = AppCustomersGroupsRouteImport.update({
  id: '/customers/groups',
  path: '/customers/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppBankVouchersRoute = AppBankVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AppBankRoute,
} as any)
const AppBankBookRoute = AppBankBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppBankRoute,
} as any)
const AppBankAccountsRoute = AppBankAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppBankRoute,
} as any)
const AppAssetsReportsRoute = AppAssetsReportsRouteImport.update({
  id: '/assets/reports',
  path: '/assets/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsReclassifyRoute = AppAssetsReclassifyRouteImport.update({
  id: '/assets/reclassify',
  path: '/assets/reclassify',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsInventoryRoute = AppAssetsInventoryRouteImport.update({
  id: '/assets/inventory',
  path: '/assets/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsFromInvoiceRoute = AppAssetsFromInvoiceRouteImport.update({
  id: '/assets/from-invoice',
  path: '/assets/from-invoice',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsFromFixedAssetRoute = AppAssetsFromFixedAssetRouteImport.update({
  id: '/assets/from-fixed-asset',
  path: '/assets/from-fixed-asset',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsEventsRoute = AppAssetsEventsRouteImport.update({
  id: '/assets/events',
  path: '/assets/events',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsDisposalRoute = AppAssetsDisposalRouteImport.update({
  id: '/assets/disposal',
  path: '/assets/disposal',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsDepreciationRoute = AppAssetsDepreciationRouteImport.update({
  id: '/assets/depreciation',
  path: '/assets/depreciation',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsCategoriesRoute = AppAssetsCategoriesRouteImport.update({
  id: '/assets/categories',
  path: '/assets/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsBooksRoute = AppAssetsBooksRouteImport.update({
  id: '/assets/books',
  path: '/assets/books',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsAllocationsRoute = AppAssetsAllocationsRouteImport.update({
  id: '/assets/allocations',
  path: '/assets/allocations',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPeriodsRoute = AppAdminPeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMembersRoute = AppAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBackupRoute = AppAdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppSuperadminTenantIdRoute = AppSuperadminTenantIdRouteImport.update({
  id: '/tenant/$id',
  path: '/tenant/$id',
  getParentRoute: () => AppSuperadminRoute,
} as any)
const AppAssetsInventoryIdRoute = AppAssetsInventoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAssetsInventoryRoute,
} as any)
const AppAssetsAllocationsIdRoute = AppAssetsAllocationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAssetsAllocationsRoute,
} as any)
const AppAssetsIdCardRoute = AppAssetsIdCardRouteImport.update({
  id: '/assets/$id/card',
  path: '/assets/$id/card',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/bank': typeof AppBankRouteWithChildren
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/items': typeof AppItemsRouteWithChildren
  '/journal': typeof AppJournalRoute
  '/setup': typeof AppSetupRoute
  '/superadmin': typeof AppSuperadminRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/backup': typeof AppAdminBackupRoute
  '/admin/members': typeof AppAdminMembersRoute
  '/admin/periods': typeof AppAdminPeriodsRoute
  '/assets/allocations': typeof AppAssetsAllocationsRouteWithChildren
  '/assets/books': typeof AppAssetsBooksRoute
  '/assets/categories': typeof AppAssetsCategoriesRoute
  '/assets/depreciation': typeof AppAssetsDepreciationRoute
  '/assets/disposal': typeof AppAssetsDisposalRoute
  '/assets/events': typeof AppAssetsEventsRoute
  '/assets/from-fixed-asset': typeof AppAssetsFromFixedAssetRoute
  '/assets/from-invoice': typeof AppAssetsFromInvoiceRoute
  '/assets/inventory': typeof AppAssetsInventoryRouteWithChildren
  '/assets/reclassify': typeof AppAssetsReclassifyRoute
  '/assets/reports': typeof AppAssetsReportsRoute
  '/bank/accounts': typeof AppBankAccountsRoute
  '/bank/book': typeof AppBankBookRoute
  '/bank/vouchers': typeof AppBankVouchersRoute
  '/customers/groups': typeof AppCustomersGroupsRoute
  '/einvoices/$id': typeof AppEinvoicesIdRoute
  '/einvoices/credentials': typeof AppEinvoicesCredentialsRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/inventory/movements': typeof AppInventoryMovementsRoute
  '/inventory/stock-card': typeof AppInventoryStockCardRoute
  '/inventory/stock-takes': typeof AppInventoryStockTakesRoute
  '/inventory/vouchers-in': typeof AppInventoryVouchersInRoute
  '/inventory/vouchers-out': typeof AppInventoryVouchersOutRoute
  '/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/items/categories': typeof AppItemsCategoriesRoute
  '/items/units': typeof AppItemsUnitsRoute
  '/payroll/$id': typeof AppPayrollIdRoute
  '/reports/allocation-schedule': typeof AppReportsAllocationScheduleRoute
  '/reports/ap-summary': typeof AppReportsApSummaryRoute
  '/reports/ar-summary': typeof AppReportsArSummaryRoute
  '/reports/ledgers': typeof AppReportsLedgersRoute
  '/reports/stock-ios': typeof AppReportsStockIosRoute
  '/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/reports/voucher-list': typeof AppReportsVoucherListRoute
  '/sales/$id': typeof AppSalesIdRoute
  '/sales/orders': typeof AppSalesOrdersRoute
  '/settings/branches': typeof AppSettingsBranchesRoute
  '/settings/cost-centers': typeof AppSettingsCostCentersRoute
  '/settings/departments': typeof AppSettingsDepartmentsRoute
  '/settings/fiscal-periods': typeof AppSettingsFiscalPeriodsRoute
  '/settings/projects': typeof AppSettingsProjectsRoute
  '/superadmin/accounts': typeof AppSuperadminAccountsRoute
  '/superadmin/audit': typeof AppSuperadminAuditRoute
  '/superadmin/organizations': typeof AppSuperadminOrganizationsRoute
  '/suppliers/$id': typeof AppSuppliersIdRoute
  '/suppliers/groups': typeof AppSuppliersGroupsRoute
  '/tax/gtgt': typeof AppTaxGtgtRoute
  '/tax/tncn': typeof AppTaxTncnRoute
  '/tax/tndn': typeof AppTaxTndnRoute
  '/admin/': typeof AppAdminIndexRoute
  '/assets/': typeof AppAssetsIndexRoute
  '/bank/': typeof AppBankIndexRoute
  '/cash/': typeof AppCashIndexRoute
  '/coa/': typeof AppCoaIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/documents/': typeof AppDocumentsIndexRoute
  '/einvoices/': typeof AppEinvoicesIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/items/': typeof AppItemsIndexRoute
  '/payables/': typeof AppPayablesIndexRoute
  '/payroll/': typeof AppPayrollIndexRoute
  '/purchases/': typeof AppPurchasesIndexRoute
  '/receipts/': typeof AppReceiptsIndexRoute
  '/receivables/': typeof AppReceivablesIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/sales-dashboard/': typeof AppSalesDashboardIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/superadmin/': typeof AppSuperadminIndexRoute
  '/suppliers/': typeof AppSuppliersIndexRoute
  '/tax/': typeof AppTaxIndexRoute
  '/assets/$id/card': typeof AppAssetsIdCardRoute
  '/assets/allocations/$id': typeof AppAssetsAllocationsIdRoute
  '/assets/inventory/$id': typeof AppAssetsInventoryIdRoute
  '/superadmin/tenant/$id': typeof AppSuperadminTenantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/journal': typeof AppJournalRoute
  '/setup': typeof AppSetupRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/backup': typeof AppAdminBackupRoute
  '/admin/members': typeof AppAdminMembersRoute
  '/admin/periods': typeof AppAdminPeriodsRoute
  '/assets/allocations': typeof AppAssetsAllocationsRouteWithChildren
  '/assets/books': typeof AppAssetsBooksRoute
  '/assets/categories': typeof AppAssetsCategoriesRoute
  '/assets/depreciation': typeof AppAssetsDepreciationRoute
  '/assets/disposal': typeof AppAssetsDisposalRoute
  '/assets/events': typeof AppAssetsEventsRoute
  '/assets/from-fixed-asset': typeof AppAssetsFromFixedAssetRoute
  '/assets/from-invoice': typeof AppAssetsFromInvoiceRoute
  '/assets/inventory': typeof AppAssetsInventoryRouteWithChildren
  '/assets/reclassify': typeof AppAssetsReclassifyRoute
  '/assets/reports': typeof AppAssetsReportsRoute
  '/bank/accounts': typeof AppBankAccountsRoute
  '/bank/book': typeof AppBankBookRoute
  '/bank/vouchers': typeof AppBankVouchersRoute
  '/customers/groups': typeof AppCustomersGroupsRoute
  '/einvoices/$id': typeof AppEinvoicesIdRoute
  '/einvoices/credentials': typeof AppEinvoicesCredentialsRoute
  '/inventory/$id': typeof AppInventoryIdRoute
  '/inventory/movements': typeof AppInventoryMovementsRoute
  '/inventory/stock-card': typeof AppInventoryStockCardRoute
  '/inventory/stock-takes': typeof AppInventoryStockTakesRoute
  '/inventory/vouchers-in': typeof AppInventoryVouchersInRoute
  '/inventory/vouchers-out': typeof AppInventoryVouchersOutRoute
  '/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/items/categories': typeof AppItemsCategoriesRoute
  '/items/units': typeof AppItemsUnitsRoute
  '/payroll/$id': typeof AppPayrollIdRoute
  '/reports/allocation-schedule': typeof AppReportsAllocationScheduleRoute
  '/reports/ap-summary': typeof AppReportsApSummaryRoute
  '/reports/ar-summary': typeof AppReportsArSummaryRoute
  '/reports/ledgers': typeof AppReportsLedgersRoute
  '/reports/stock-ios': typeof AppReportsStockIosRoute
  '/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/reports/voucher-list': typeof AppReportsVoucherListRoute
  '/sales/$id': typeof AppSalesIdRoute
  '/sales/orders': typeof AppSalesOrdersRoute
  '/settings/branches': typeof AppSettingsBranchesRoute
  '/settings/cost-centers': typeof AppSettingsCostCentersRoute
  '/settings/departments': typeof AppSettingsDepartmentsRoute
  '/settings/fiscal-periods': typeof AppSettingsFiscalPeriodsRoute
  '/settings/projects': typeof AppSettingsProjectsRoute
  '/superadmin/accounts': typeof AppSuperadminAccountsRoute
  '/superadmin/audit': typeof AppSuperadminAuditRoute
  '/superadmin/organizations': typeof AppSuperadminOrganizationsRoute
  '/suppliers/$id': typeof AppSuppliersIdRoute
  '/suppliers/groups': typeof AppSuppliersGroupsRoute
  '/tax/gtgt': typeof AppTaxGtgtRoute
  '/tax/tncn': typeof AppTaxTncnRoute
  '/tax/tndn': typeof AppTaxTndnRoute
  '/admin': typeof AppAdminIndexRoute
  '/assets': typeof AppAssetsIndexRoute
  '/bank': typeof AppBankIndexRoute
  '/cash': typeof AppCashIndexRoute
  '/coa': typeof AppCoaIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/einvoices': typeof AppEinvoicesIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/items': typeof AppItemsIndexRoute
  '/payables': typeof AppPayablesIndexRoute
  '/payroll': typeof AppPayrollIndexRoute
  '/purchases': typeof AppPurchasesIndexRoute
  '/receipts': typeof AppReceiptsIndexRoute
  '/receivables': typeof AppReceivablesIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/sales-dashboard': typeof AppSalesDashboardIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/superadmin': typeof AppSuperadminIndexRoute
  '/suppliers': typeof AppSuppliersIndexRoute
  '/tax': typeof AppTaxIndexRoute
  '/assets/$id/card': typeof AppAssetsIdCardRoute
  '/assets/allocations/$id': typeof AppAssetsAllocationsIdRoute
  '/assets/inventory/$id': typeof AppAssetsInventoryIdRoute
  '/superadmin/tenant/$id': typeof AppSuperadminTenantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/bank': typeof AppBankRouteWithChildren
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/items': typeof AppItemsRouteWithChildren
  '/_app/journal': typeof AppJournalRoute
  '/_app/setup': typeof AppSetupRoute
  '/_app/superadmin': typeof AppSuperadminRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/backup': typeof AppAdminBackupRoute
  '/_app/admin/members': typeof AppAdminMembersRoute
  '/_app/admin/periods': typeof AppAdminPeriodsRoute
  '/_app/assets/allocations': typeof AppAssetsAllocationsRouteWithChildren
  '/_app/assets/books': typeof AppAssetsBooksRoute
  '/_app/assets/categories': typeof AppAssetsCategoriesRoute
  '/_app/assets/depreciation': typeof AppAssetsDepreciationRoute
  '/_app/assets/disposal': typeof AppAssetsDisposalRoute
  '/_app/assets/events': typeof AppAssetsEventsRoute
  '/_app/assets/from-fixed-asset': typeof AppAssetsFromFixedAssetRoute
  '/_app/assets/from-invoice': typeof AppAssetsFromInvoiceRoute
  '/_app/assets/inventory': typeof AppAssetsInventoryRouteWithChildren
  '/_app/assets/reclassify': typeof AppAssetsReclassifyRoute
  '/_app/assets/reports': typeof AppAssetsReportsRoute
  '/_app/bank/accounts': typeof AppBankAccountsRoute
  '/_app/bank/book': typeof AppBankBookRoute
  '/_app/bank/vouchers': typeof AppBankVouchersRoute
  '/_app/customers/groups': typeof AppCustomersGroupsRoute
  '/_app/einvoices/$id': typeof AppEinvoicesIdRoute
  '/_app/einvoices/credentials': typeof AppEinvoicesCredentialsRoute
  '/_app/inventory/$id': typeof AppInventoryIdRoute
  '/_app/inventory/movements': typeof AppInventoryMovementsRoute
  '/_app/inventory/stock-card': typeof AppInventoryStockCardRoute
  '/_app/inventory/stock-takes': typeof AppInventoryStockTakesRoute
  '/_app/inventory/vouchers-in': typeof AppInventoryVouchersInRoute
  '/_app/inventory/vouchers-out': typeof AppInventoryVouchersOutRoute
  '/_app/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/items/categories': typeof AppItemsCategoriesRoute
  '/_app/items/units': typeof AppItemsUnitsRoute
  '/_app/payroll/$id': typeof AppPayrollIdRoute
  '/_app/reports/allocation-schedule': typeof AppReportsAllocationScheduleRoute
  '/_app/reports/ap-summary': typeof AppReportsApSummaryRoute
  '/_app/reports/ar-summary': typeof AppReportsArSummaryRoute
  '/_app/reports/ledgers': typeof AppReportsLedgersRoute
  '/_app/reports/stock-ios': typeof AppReportsStockIosRoute
  '/_app/reports/trial-balance': typeof AppReportsTrialBalanceRoute
  '/_app/reports/voucher-list': typeof AppReportsVoucherListRoute
  '/_app/sales/$id': typeof AppSalesIdRoute
  '/_app/sales/orders': typeof AppSalesOrdersRoute
  '/_app/settings/branches': typeof AppSettingsBranchesRoute
  '/_app/settings/cost-centers': typeof AppSettingsCostCentersRoute
  '/_app/settings/departments': typeof AppSettingsDepartmentsRoute
  '/_app/settings/fiscal-periods': typeof AppSettingsFiscalPeriodsRoute
  '/_app/settings/projects': typeof AppSettingsProjectsRoute
  '/_app/superadmin/accounts': typeof AppSuperadminAccountsRoute
  '/_app/superadmin/audit': typeof AppSuperadminAuditRoute
  '/_app/superadmin/organizations': typeof AppSuperadminOrganizationsRoute
  '/_app/suppliers/$id': typeof AppSuppliersIdRoute
  '/_app/suppliers/groups': typeof AppSuppliersGroupsRoute
  '/_app/tax/gtgt': typeof AppTaxGtgtRoute
  '/_app/tax/tncn': typeof AppTaxTncnRoute
  '/_app/tax/tndn': typeof AppTaxTndnRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/bank/': typeof AppBankIndexRoute
  '/_app/cash/': typeof AppCashIndexRoute
  '/_app/coa/': typeof AppCoaIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/_app/einvoices/': typeof AppEinvoicesIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/items/': typeof AppItemsIndexRoute
  '/_app/payables/': typeof AppPayablesIndexRoute
  '/_app/payroll/': typeof AppPayrollIndexRoute
  '/_app/purchases/': typeof AppPurchasesIndexRoute
  '/_app/receipts/': typeof AppReceiptsIndexRoute
  '/_app/receivables/': typeof AppReceivablesIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/sales-dashboard/': typeof AppSalesDashboardIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/superadmin/': typeof AppSuperadminIndexRoute
  '/_app/suppliers/': typeof AppSuppliersIndexRoute
  '/_app/tax/': typeof AppTaxIndexRoute
  '/_app/assets/$id/card': typeof AppAssetsIdCardRoute
  '/_app/assets/allocations/$id': typeof AppAssetsAllocationsIdRoute
  '/_app/assets/inventory/$id': typeof AppAssetsInventoryIdRoute
  '/_app/superadmin/tenant/$id': typeof AppSuperadminTenantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/bank'
    | '/chat'
    | '/dashboard'
    | '/inventory'
    | '/items'
    | '/journal'
    | '/setup'
    | '/superadmin'
    | '/invite/$token'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/members'
    | '/admin/periods'
    | '/assets/allocations'
    | '/assets/books'
    | '/assets/categories'
    | '/assets/depreciation'
    | '/assets/disposal'
    | '/assets/events'
    | '/assets/from-fixed-asset'
    | '/assets/from-invoice'
    | '/assets/inventory'
    | '/assets/reclassify'
    | '/assets/reports'
    | '/bank/accounts'
    | '/bank/book'
    | '/bank/vouchers'
    | '/customers/groups'
    | '/einvoices/$id'
    | '/einvoices/credentials'
    | '/inventory/$id'
    | '/inventory/movements'
    | '/inventory/stock-card'
    | '/inventory/stock-takes'
    | '/inventory/vouchers-in'
    | '/inventory/vouchers-out'
    | '/inventory/warehouses'
    | '/invoices/$id'
    | '/items/categories'
    | '/items/units'
    | '/payroll/$id'
    | '/reports/allocation-schedule'
    | '/reports/ap-summary'
    | '/reports/ar-summary'
    | '/reports/ledgers'
    | '/reports/stock-ios'
    | '/reports/trial-balance'
    | '/reports/voucher-list'
    | '/sales/$id'
    | '/sales/orders'
    | '/settings/branches'
    | '/settings/cost-centers'
    | '/settings/departments'
    | '/settings/fiscal-periods'
    | '/settings/projects'
    | '/superadmin/accounts'
    | '/superadmin/audit'
    | '/superadmin/organizations'
    | '/suppliers/$id'
    | '/suppliers/groups'
    | '/tax/gtgt'
    | '/tax/tncn'
    | '/tax/tndn'
    | '/admin/'
    | '/assets/'
    | '/bank/'
    | '/cash/'
    | '/coa/'
    | '/customers/'
    | '/documents/'
    | '/einvoices/'
    | '/inventory/'
    | '/invoices/'
    | '/items/'
    | '/payables/'
    | '/payroll/'
    | '/purchases/'
    | '/receipts/'
    | '/receivables/'
    | '/reports/'
    | '/sales-dashboard/'
    | '/sales/'
    | '/settings/'
    | '/superadmin/'
    | '/suppliers/'
    | '/tax/'
    | '/assets/$id/card'
    | '/assets/allocations/$id'
    | '/assets/inventory/$id'
    | '/superadmin/tenant/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/chat'
    | '/dashboard'
    | '/journal'
    | '/setup'
    | '/invite/$token'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/members'
    | '/admin/periods'
    | '/assets/allocations'
    | '/assets/books'
    | '/assets/categories'
    | '/assets/depreciation'
    | '/assets/disposal'
    | '/assets/events'
    | '/assets/from-fixed-asset'
    | '/assets/from-invoice'
    | '/assets/inventory'
    | '/assets/reclassify'
    | '/assets/reports'
    | '/bank/accounts'
    | '/bank/book'
    | '/bank/vouchers'
    | '/customers/groups'
    | '/einvoices/$id'
    | '/einvoices/credentials'
    | '/inventory/$id'
    | '/inventory/movements'
    | '/inventory/stock-card'
    | '/inventory/stock-takes'
    | '/inventory/vouchers-in'
    | '/inventory/vouchers-out'
    | '/inventory/warehouses'
    | '/invoices/$id'
    | '/items/categories'
    | '/items/units'
    | '/payroll/$id'
    | '/reports/allocation-schedule'
    | '/reports/ap-summary'
    | '/reports/ar-summary'
    | '/reports/ledgers'
    | '/reports/stock-ios'
    | '/reports/trial-balance'
    | '/reports/voucher-list'
    | '/sales/$id'
    | '/sales/orders'
    | '/settings/branches'
    | '/settings/cost-centers'
    | '/settings/departments'
    | '/settings/fiscal-periods'
    | '/settings/projects'
    | '/superadmin/accounts'
    | '/superadmin/audit'
    | '/superadmin/organizations'
    | '/suppliers/$id'
    | '/suppliers/groups'
    | '/tax/gtgt'
    | '/tax/tncn'
    | '/tax/tndn'
    | '/admin'
    | '/assets'
    | '/bank'
    | '/cash'
    | '/coa'
    | '/customers'
    | '/documents'
    | '/einvoices'
    | '/inventory'
    | '/invoices'
    | '/items'
    | '/payables'
    | '/payroll'
    | '/purchases'
    | '/receipts'
    | '/receivables'
    | '/reports'
    | '/sales-dashboard'
    | '/sales'
    | '/settings'
    | '/superadmin'
    | '/suppliers'
    | '/tax'
    | '/assets/$id/card'
    | '/assets/allocations/$id'
    | '/assets/inventory/$id'
    | '/superadmin/tenant/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/bank'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/items'
    | '/_app/journal'
    | '/_app/setup'
    | '/_app/superadmin'
    | '/invite/$token'
    | '/_app/admin/audit'
    | '/_app/admin/backup'
    | '/_app/admin/members'
    | '/_app/admin/periods'
    | '/_app/assets/allocations'
    | '/_app/assets/books'
    | '/_app/assets/categories'
    | '/_app/assets/depreciation'
    | '/_app/assets/disposal'
    | '/_app/assets/events'
    | '/_app/assets/from-fixed-asset'
    | '/_app/assets/from-invoice'
    | '/_app/assets/inventory'
    | '/_app/assets/reclassify'
    | '/_app/assets/reports'
    | '/_app/bank/accounts'
    | '/_app/bank/book'
    | '/_app/bank/vouchers'
    | '/_app/customers/groups'
    | '/_app/einvoices/$id'
    | '/_app/einvoices/credentials'
    | '/_app/inventory/$id'
    | '/_app/inventory/movements'
    | '/_app/inventory/stock-card'
    | '/_app/inventory/stock-takes'
    | '/_app/inventory/vouchers-in'
    | '/_app/inventory/vouchers-out'
    | '/_app/inventory/warehouses'
    | '/_app/invoices/$id'
    | '/_app/items/categories'
    | '/_app/items/units'
    | '/_app/payroll/$id'
    | '/_app/reports/allocation-schedule'
    | '/_app/reports/ap-summary'
    | '/_app/reports/ar-summary'
    | '/_app/reports/ledgers'
    | '/_app/reports/stock-ios'
    | '/_app/reports/trial-balance'
    | '/_app/reports/voucher-list'
    | '/_app/sales/$id'
    | '/_app/sales/orders'
    | '/_app/settings/branches'
    | '/_app/settings/cost-centers'
    | '/_app/settings/departments'
    | '/_app/settings/fiscal-periods'
    | '/_app/settings/projects'
    | '/_app/superadmin/accounts'
    | '/_app/superadmin/audit'
    | '/_app/superadmin/organizations'
    | '/_app/suppliers/$id'
    | '/_app/suppliers/groups'
    | '/_app/tax/gtgt'
    | '/_app/tax/tncn'
    | '/_app/tax/tndn'
    | '/_app/admin/'
    | '/_app/assets/'
    | '/_app/bank/'
    | '/_app/cash/'
    | '/_app/coa/'
    | '/_app/customers/'
    | '/_app/documents/'
    | '/_app/einvoices/'
    | '/_app/inventory/'
    | '/_app/invoices/'
    | '/_app/items/'
    | '/_app/payables/'
    | '/_app/payroll/'
    | '/_app/purchases/'
    | '/_app/receipts/'
    | '/_app/receivables/'
    | '/_app/reports/'
    | '/_app/sales-dashboard/'
    | '/_app/sales/'
    | '/_app/settings/'
    | '/_app/superadmin/'
    | '/_app/suppliers/'
    | '/_app/tax/'
    | '/_app/assets/$id/card'
    | '/_app/assets/allocations/$id'
    | '/_app/assets/inventory/$id'
    | '/_app/superadmin/tenant/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/superadmin': {
      id: '/_app/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AppSuperadminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup': {
      id: '/_app/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/items': {
      id: '/_app/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AppItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank': {
      id: '/_app/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tax/': {
      id: '/_app/tax/'
      path: '/tax'
      fullPath: '/tax/'
      preLoaderRoute: typeof AppTaxIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/': {
      id: '/_app/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/superadmin/': {
      id: '/_app/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof AppSuperadminIndexRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-dashboard/': {
      id: '/_app/sales-dashboard/'
      path: '/sales-dashboard'
      fullPath: '/sales-dashboard/'
      preLoaderRoute: typeof AppSalesDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receivables/': {
      id: '/_app/receivables/'
      path: '/receivables'
      fullPath: '/receivables/'
      preLoaderRoute: typeof AppReceivablesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receipts/': {
      id: '/_app/receipts/'
      path: '/receipts'
      fullPath: '/receipts/'
      preLoaderRoute: typeof AppReceiptsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases/': {
      id: '/_app/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AppPurchasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/': {
      id: '/_app/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof AppPayrollIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payables/': {
      id: '/_app/payables/'
      path: '/payables'
      fullPath: '/payables/'
      preLoaderRoute: typeof AppPayablesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/items/': {
      id: '/_app/items/'
      path: '/'
      fullPath: '/items/'
      preLoaderRoute: typeof AppItemsIndexRouteImport
      parentRoute: typeof AppItemsRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/einvoices/': {
      id: '/_app/einvoices/'
      path: '/einvoices'
      fullPath: '/einvoices/'
      preLoaderRoute: typeof AppEinvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coa/': {
      id: '/_app/coa/'
      path: '/coa'
      fullPath: '/coa/'
      preLoaderRoute: typeof AppCoaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash/': {
      id: '/_app/cash/'
      path: '/cash'
      fullPath: '/cash/'
      preLoaderRoute: typeof AppCashIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank/': {
      id: '/_app/bank/'
      path: '/'
      fullPath: '/bank/'
      preLoaderRoute: typeof AppBankIndexRouteImport
      parentRoute: typeof AppBankRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/tax/tndn': {
      id: '/_app/tax/tndn'
      path: '/tax/tndn'
      fullPath: '/tax/tndn'
      preLoaderRoute: typeof AppTaxTndnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tax/tncn': {
      id: '/_app/tax/tncn'
      path: '/tax/tncn'
      fullPath: '/tax/tncn'
      preLoaderRoute: typeof AppTaxTncnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tax/gtgt': {
      id: '/_app/tax/gtgt'
      path: '/tax/gtgt'
      fullPath: '/tax/gtgt'
      preLoaderRoute: typeof AppTaxGtgtRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/groups': {
      id: '/_app/suppliers/groups'
      path: '/suppliers/groups'
      fullPath: '/suppliers/groups'
      preLoaderRoute: typeof AppSuppliersGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/$id': {
      id: '/_app/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof AppSuppliersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/superadmin/organizations': {
      id: '/_app/superadmin/organizations'
      path: '/organizations'
      fullPath: '/superadmin/organizations'
      preLoaderRoute: typeof AppSuperadminOrganizationsRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/superadmin/audit': {
      id: '/_app/superadmin/audit'
      path: '/audit'
      fullPath: '/superadmin/audit'
      preLoaderRoute: typeof AppSuperadminAuditRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/superadmin/accounts': {
      id: '/_app/superadmin/accounts'
      path: '/accounts'
      fullPath: '/superadmin/accounts'
      preLoaderRoute: typeof AppSuperadminAccountsRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/settings/projects': {
      id: '/_app/settings/projects'
      path: '/settings/projects'
      fullPath: '/settings/projects'
      preLoaderRoute: typeof AppSettingsProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/fiscal-periods': {
      id: '/_app/settings/fiscal-periods'
      path: '/settings/fiscal-periods'
      fullPath: '/settings/fiscal-periods'
      preLoaderRoute: typeof AppSettingsFiscalPeriodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/departments': {
      id: '/_app/settings/departments'
      path: '/settings/departments'
      fullPath: '/settings/departments'
      preLoaderRoute: typeof AppSettingsDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/cost-centers': {
      id: '/_app/settings/cost-centers'
      path: '/settings/cost-centers'
      fullPath: '/settings/cost-centers'
      preLoaderRoute: typeof AppSettingsCostCentersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/branches': {
      id: '/_app/settings/branches'
      path: '/settings/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof AppSettingsBranchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/orders': {
      id: '/_app/sales/orders'
      path: '/sales/orders'
      fullPath: '/sales/orders'
      preLoaderRoute: typeof AppSalesOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/$id': {
      id: '/_app/sales/$id'
      path: '/sales/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof AppSalesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/voucher-list': {
      id: '/_app/reports/voucher-list'
      path: '/reports/voucher-list'
      fullPath: '/reports/voucher-list'
      preLoaderRoute: typeof AppReportsVoucherListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/trial-balance': {
      id: '/_app/reports/trial-balance'
      path: '/reports/trial-balance'
      fullPath: '/reports/trial-balance'
      preLoaderRoute: typeof AppReportsTrialBalanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/stock-ios': {
      id: '/_app/reports/stock-ios'
      path: '/reports/stock-ios'
      fullPath: '/reports/stock-ios'
      preLoaderRoute: typeof AppReportsStockIosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/ledgers': {
      id: '/_app/reports/ledgers'
      path: '/reports/ledgers'
      fullPath: '/reports/ledgers'
      preLoaderRoute: typeof AppReportsLedgersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/ar-summary': {
      id: '/_app/reports/ar-summary'
      path: '/reports/ar-summary'
      fullPath: '/reports/ar-summary'
      preLoaderRoute: typeof AppReportsArSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/ap-summary': {
      id: '/_app/reports/ap-summary'
      path: '/reports/ap-summary'
      fullPath: '/reports/ap-summary'
      preLoaderRoute: typeof AppReportsApSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/allocation-schedule': {
      id: '/_app/reports/allocation-schedule'
      path: '/reports/allocation-schedule'
      fullPath: '/reports/allocation-schedule'
      preLoaderRoute: typeof AppReportsAllocationScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/$id': {
      id: '/_app/payroll/$id'
      path: '/payroll/$id'
      fullPath: '/payroll/$id'
      preLoaderRoute: typeof AppPayrollIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/items/units': {
      id: '/_app/items/units'
      path: '/units'
      fullPath: '/items/units'
      preLoaderRoute: typeof AppItemsUnitsRouteImport
      parentRoute: typeof AppItemsRoute
    }
    '/_app/items/categories': {
      id: '/_app/items/categories'
      path: '/categories'
      fullPath: '/items/categories'
      preLoaderRoute: typeof AppItemsCategoriesRouteImport
      parentRoute: typeof AppItemsRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/warehouses': {
      id: '/_app/inventory/warehouses'
      path: '/warehouses'
      fullPath: '/inventory/warehouses'
      preLoaderRoute: typeof AppInventoryWarehousesRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/vouchers-out': {
      id: '/_app/inventory/vouchers-out'
      path: '/vouchers-out'
      fullPath: '/inventory/vouchers-out'
      preLoaderRoute: typeof AppInventoryVouchersOutRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/vouchers-in': {
      id: '/_app/inventory/vouchers-in'
      path: '/vouchers-in'
      fullPath: '/inventory/vouchers-in'
      preLoaderRoute: typeof AppInventoryVouchersInRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/stock-takes': {
      id: '/_app/inventory/stock-takes'
      path: '/stock-takes'
      fullPath: '/inventory/stock-takes'
      preLoaderRoute: typeof AppInventoryStockTakesRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/stock-card': {
      id: '/_app/inventory/stock-card'
      path: '/stock-card'
      fullPath: '/inventory/stock-card'
      preLoaderRoute: typeof AppInventoryStockCardRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/movements': {
      id: '/_app/inventory/movements'
      path: '/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof AppInventoryMovementsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/$id': {
      id: '/_app/inventory/$id'
      path: '/$id'
      fullPath: '/inventory/$id'
      preLoaderRoute: typeof AppInventoryIdRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/einvoices/credentials': {
      id: '/_app/einvoices/credentials'
      path: '/einvoices/credentials'
      fullPath: '/einvoices/credentials'
      preLoaderRoute: typeof AppEinvoicesCredentialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/einvoices/$id': {
      id: '/_app/einvoices/$id'
      path: '/einvoices/$id'
      fullPath: '/einvoices/$id'
      preLoaderRoute: typeof AppEinvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/groups': {
      id: '/_app/customers/groups'
      path: '/customers/groups'
      fullPath: '/customers/groups'
      preLoaderRoute: typeof AppCustomersGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank/vouchers': {
      id: '/_app/bank/vouchers'
      path: '/vouchers'
      fullPath: '/bank/vouchers'
      preLoaderRoute: typeof AppBankVouchersRouteImport
      parentRoute: typeof AppBankRoute
    }
    '/_app/bank/book': {
      id: '/_app/bank/book'
      path: '/book'
      fullPath: '/bank/book'
      preLoaderRoute: typeof AppBankBookRouteImport
      parentRoute: typeof AppBankRoute
    }
    '/_app/bank/accounts': {
      id: '/_app/bank/accounts'
      path: '/accounts'
      fullPath: '/bank/accounts'
      preLoaderRoute: typeof AppBankAccountsRouteImport
      parentRoute: typeof AppBankRoute
    }
    '/_app/assets/reports': {
      id: '/_app/assets/reports'
      path: '/assets/reports'
      fullPath: '/assets/reports'
      preLoaderRoute: typeof AppAssetsReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/reclassify': {
      id: '/_app/assets/reclassify'
      path: '/assets/reclassify'
      fullPath: '/assets/reclassify'
      preLoaderRoute: typeof AppAssetsReclassifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/inventory': {
      id: '/_app/assets/inventory'
      path: '/assets/inventory'
      fullPath: '/assets/inventory'
      preLoaderRoute: typeof AppAssetsInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/from-invoice': {
      id: '/_app/assets/from-invoice'
      path: '/assets/from-invoice'
      fullPath: '/assets/from-invoice'
      preLoaderRoute: typeof AppAssetsFromInvoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/from-fixed-asset': {
      id: '/_app/assets/from-fixed-asset'
      path: '/assets/from-fixed-asset'
      fullPath: '/assets/from-fixed-asset'
      preLoaderRoute: typeof AppAssetsFromFixedAssetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/events': {
      id: '/_app/assets/events'
      path: '/assets/events'
      fullPath: '/assets/events'
      preLoaderRoute: typeof AppAssetsEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/disposal': {
      id: '/_app/assets/disposal'
      path: '/assets/disposal'
      fullPath: '/assets/disposal'
      preLoaderRoute: typeof AppAssetsDisposalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/depreciation': {
      id: '/_app/assets/depreciation'
      path: '/assets/depreciation'
      fullPath: '/assets/depreciation'
      preLoaderRoute: typeof AppAssetsDepreciationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/categories': {
      id: '/_app/assets/categories'
      path: '/assets/categories'
      fullPath: '/assets/categories'
      preLoaderRoute: typeof AppAssetsCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/books': {
      id: '/_app/assets/books'
      path: '/assets/books'
      fullPath: '/assets/books'
      preLoaderRoute: typeof AppAssetsBooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/allocations': {
      id: '/_app/assets/allocations'
      path: '/assets/allocations'
      fullPath: '/assets/allocations'
      preLoaderRoute: typeof AppAssetsAllocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/periods': {
      id: '/_app/admin/periods'
      path: '/periods'
      fullPath: '/admin/periods'
      preLoaderRoute: typeof AppAdminPeriodsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/members': {
      id: '/_app/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AppAdminMembersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/backup': {
      id: '/_app/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AppAdminBackupRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/superadmin/tenant/$id': {
      id: '/_app/superadmin/tenant/$id'
      path: '/tenant/$id'
      fullPath: '/superadmin/tenant/$id'
      preLoaderRoute: typeof AppSuperadminTenantIdRouteImport
      parentRoute: typeof AppSuperadminRoute
    }
    '/_app/assets/inventory/$id': {
      id: '/_app/assets/inventory/$id'
      path: '/$id'
      fullPath: '/assets/inventory/$id'
      preLoaderRoute: typeof AppAssetsInventoryIdRouteImport
      parentRoute: typeof AppAssetsInventoryRoute
    }
    '/_app/assets/allocations/$id': {
      id: '/_app/assets/allocations/$id'
      path: '/$id'
      fullPath: '/assets/allocations/$id'
      preLoaderRoute: typeof AppAssetsAllocationsIdRouteImport
      parentRoute: typeof AppAssetsAllocationsRoute
    }
    '/_app/assets/$id/card': {
      id: '/_app/assets/$id/card'
      path: '/assets/$id/card'
      fullPath: '/assets/$id/card'
      preLoaderRoute: typeof AppAssetsIdCardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminBackupRoute: typeof AppAdminBackupRoute
  AppAdminMembersRoute: typeof AppAdminMembersRoute
  AppAdminPeriodsRoute: typeof AppAdminPeriodsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminBackupRoute: AppAdminBackupRoute,
  AppAdminMembersRoute: AppAdminMembersRoute,
  AppAdminPeriodsRoute: AppAdminPeriodsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppBankRouteChildren {
  AppBankAccountsRoute: typeof AppBankAccountsRoute
  AppBankBookRoute: typeof AppBankBookRoute
  AppBankVouchersRoute: typeof AppBankVouchersRoute
  AppBankIndexRoute: typeof AppBankIndexRoute
}

const AppBankRouteChildren: AppBankRouteChildren = {
  AppBankAccountsRoute: AppBankAccountsRoute,
  AppBankBookRoute: AppBankBookRoute,
  AppBankVouchersRoute: AppBankVouchersRoute,
  AppBankIndexRoute: AppBankIndexRoute,
}

const AppBankRouteWithChildren =
  AppBankRoute._addFileChildren(AppBankRouteChildren)

interface AppInventoryRouteChildren {
  AppInventoryIdRoute: typeof AppInventoryIdRoute
  AppInventoryMovementsRoute: typeof AppInventoryMovementsRoute
  AppInventoryStockCardRoute: typeof AppInventoryStockCardRoute
  AppInventoryStockTakesRoute: typeof AppInventoryStockTakesRoute
  AppInventoryVouchersInRoute: typeof AppInventoryVouchersInRoute
  AppInventoryVouchersOutRoute: typeof AppInventoryVouchersOutRoute
  AppInventoryWarehousesRoute: typeof AppInventoryWarehousesRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryIdRoute: AppInventoryIdRoute,
  AppInventoryMovementsRoute: AppInventoryMovementsRoute,
  AppInventoryStockCardRoute: AppInventoryStockCardRoute,
  AppInventoryStockTakesRoute: AppInventoryStockTakesRoute,
  AppInventoryVouchersInRoute: AppInventoryVouchersInRoute,
  AppInventoryVouchersOutRoute: AppInventoryVouchersOutRoute,
  AppInventoryWarehousesRoute: AppInventoryWarehousesRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppItemsRouteChildren {
  AppItemsCategoriesRoute: typeof AppItemsCategoriesRoute
  AppItemsUnitsRoute: typeof AppItemsUnitsRoute
  AppItemsIndexRoute: typeof AppItemsIndexRoute
}

const AppItemsRouteChildren: AppItemsRouteChildren = {
  AppItemsCategoriesRoute: AppItemsCategoriesRoute,
  AppItemsUnitsRoute: AppItemsUnitsRoute,
  AppItemsIndexRoute: AppItemsIndexRoute,
}

const AppItemsRouteWithChildren = AppItemsRoute._addFileChildren(
  AppItemsRouteChildren,
)

interface AppSuperadminRouteChildren {
  AppSuperadminAccountsRoute: typeof AppSuperadminAccountsRoute
  AppSuperadminAuditRoute: typeof AppSuperadminAuditRoute
  AppSuperadminOrganizationsRoute: typeof AppSuperadminOrganizationsRoute
  AppSuperadminIndexRoute: typeof AppSuperadminIndexRoute
  AppSuperadminTenantIdRoute: typeof AppSuperadminTenantIdRoute
}

const AppSuperadminRouteChildren: AppSuperadminRouteChildren = {
  AppSuperadminAccountsRoute: AppSuperadminAccountsRoute,
  AppSuperadminAuditRoute: AppSuperadminAuditRoute,
  AppSuperadminOrganizationsRoute: AppSuperadminOrganizationsRoute,
  AppSuperadminIndexRoute: AppSuperadminIndexRoute,
  AppSuperadminTenantIdRoute: AppSuperadminTenantIdRoute,
}

const AppSuperadminRouteWithChildren = AppSuperadminRoute._addFileChildren(
  AppSuperadminRouteChildren,
)

interface AppAssetsAllocationsRouteChildren {
  AppAssetsAllocationsIdRoute: typeof AppAssetsAllocationsIdRoute
}

const AppAssetsAllocationsRouteChildren: AppAssetsAllocationsRouteChildren = {
  AppAssetsAllocationsIdRoute: AppAssetsAllocationsIdRoute,
}

const AppAssetsAllocationsRouteWithChildren =
  AppAssetsAllocationsRoute._addFileChildren(AppAssetsAllocationsRouteChildren)

interface AppAssetsInventoryRouteChildren {
  AppAssetsInventoryIdRoute: typeof AppAssetsInventoryIdRoute
}

const AppAssetsInventoryRouteChildren: AppAssetsInventoryRouteChildren = {
  AppAssetsInventoryIdRoute: AppAssetsInventoryIdRoute,
}

const AppAssetsInventoryRouteWithChildren =
  AppAssetsInventoryRoute._addFileChildren(AppAssetsInventoryRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppBankRoute: typeof AppBankRouteWithChildren
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppItemsRoute: typeof AppItemsRouteWithChildren
  AppJournalRoute: typeof AppJournalRoute
  AppSetupRoute: typeof AppSetupRoute
  AppSuperadminRoute: typeof AppSuperadminRouteWithChildren
  AppAssetsAllocationsRoute: typeof AppAssetsAllocationsRouteWithChildren
  AppAssetsBooksRoute: typeof AppAssetsBooksRoute
  AppAssetsCategoriesRoute: typeof AppAssetsCategoriesRoute
  AppAssetsDepreciationRoute: typeof AppAssetsDepreciationRoute
  AppAssetsDisposalRoute: typeof AppAssetsDisposalRoute
  AppAssetsEventsRoute: typeof AppAssetsEventsRoute
  AppAssetsFromFixedAssetRoute: typeof AppAssetsFromFixedAssetRoute
  AppAssetsFromInvoiceRoute: typeof AppAssetsFromInvoiceRoute
  AppAssetsInventoryRoute: typeof AppAssetsInventoryRouteWithChildren
  AppAssetsReclassifyRoute: typeof AppAssetsReclassifyRoute
  AppAssetsReportsRoute: typeof AppAssetsReportsRoute
  AppCustomersGroupsRoute: typeof AppCustomersGroupsRoute
  AppEinvoicesIdRoute: typeof AppEinvoicesIdRoute
  AppEinvoicesCredentialsRoute: typeof AppEinvoicesCredentialsRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppPayrollIdRoute: typeof AppPayrollIdRoute
  AppReportsAllocationScheduleRoute: typeof AppReportsAllocationScheduleRoute
  AppReportsApSummaryRoute: typeof AppReportsApSummaryRoute
  AppReportsArSummaryRoute: typeof AppReportsArSummaryRoute
  AppReportsLedgersRoute: typeof AppReportsLedgersRoute
  AppReportsStockIosRoute: typeof AppReportsStockIosRoute
  AppReportsTrialBalanceRoute: typeof AppReportsTrialBalanceRoute
  AppReportsVoucherListRoute: typeof AppReportsVoucherListRoute
  AppSalesIdRoute: typeof AppSalesIdRoute
  AppSalesOrdersRoute: typeof AppSalesOrdersRoute
  AppSettingsBranchesRoute: typeof AppSettingsBranchesRoute
  AppSettingsCostCentersRoute: typeof AppSettingsCostCentersRoute
  AppSettingsDepartmentsRoute: typeof AppSettingsDepartmentsRoute
  AppSettingsFiscalPeriodsRoute: typeof AppSettingsFiscalPeriodsRoute
  AppSettingsProjectsRoute: typeof AppSettingsProjectsRoute
  AppSuppliersIdRoute: typeof AppSuppliersIdRoute
  AppSuppliersGroupsRoute: typeof AppSuppliersGroupsRoute
  AppTaxGtgtRoute: typeof AppTaxGtgtRoute
  AppTaxTncnRoute: typeof AppTaxTncnRoute
  AppTaxTndnRoute: typeof AppTaxTndnRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppCashIndexRoute: typeof AppCashIndexRoute
  AppCoaIndexRoute: typeof AppCoaIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppEinvoicesIndexRoute: typeof AppEinvoicesIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppPayablesIndexRoute: typeof AppPayablesIndexRoute
  AppPayrollIndexRoute: typeof AppPayrollIndexRoute
  AppPurchasesIndexRoute: typeof AppPurchasesIndexRoute
  AppReceiptsIndexRoute: typeof AppReceiptsIndexRoute
  AppReceivablesIndexRoute: typeof AppReceivablesIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSalesDashboardIndexRoute: typeof AppSalesDashboardIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
  AppTaxIndexRoute: typeof AppTaxIndexRoute
  AppAssetsIdCardRoute: typeof AppAssetsIdCardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppBankRoute: AppBankRouteWithChildren,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppItemsRoute: AppItemsRouteWithChildren,
  AppJournalRoute: AppJournalRoute,
  AppSetupRoute: AppSetupRoute,
  AppSuperadminRoute: AppSuperadminRouteWithChildren,
  AppAssetsAllocationsRoute: AppAssetsAllocationsRouteWithChildren,
  AppAssetsBooksRoute: AppAssetsBooksRoute,
  AppAssetsCategoriesRoute: AppAssetsCategoriesRoute,
  AppAssetsDepreciationRoute: AppAssetsDepreciationRoute,
  AppAssetsDisposalRoute: AppAssetsDisposalRoute,
  AppAssetsEventsRoute: AppAssetsEventsRoute,
  AppAssetsFromFixedAssetRoute: AppAssetsFromFixedAssetRoute,
  AppAssetsFromInvoiceRoute: AppAssetsFromInvoiceRoute,
  AppAssetsInventoryRoute: AppAssetsInventoryRouteWithChildren,
  AppAssetsReclassifyRoute: AppAssetsReclassifyRoute,
  AppAssetsReportsRoute: AppAssetsReportsRoute,
  AppCustomersGroupsRoute: AppCustomersGroupsRoute,
  AppEinvoicesIdRoute: AppEinvoicesIdRoute,
  AppEinvoicesCredentialsRoute: AppEinvoicesCredentialsRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppPayrollIdRoute: AppPayrollIdRoute,
  AppReportsAllocationScheduleRoute: AppReportsAllocationScheduleRoute,
  AppReportsApSummaryRoute: AppReportsApSummaryRoute,
  AppReportsArSummaryRoute: AppReportsArSummaryRoute,
  AppReportsLedgersRoute: AppReportsLedgersRoute,
  AppReportsStockIosRoute: AppReportsStockIosRoute,
  AppReportsTrialBalanceRoute: AppReportsTrialBalanceRoute,
  AppReportsVoucherListRoute: AppReportsVoucherListRoute,
  AppSalesIdRoute: AppSalesIdRoute,
  AppSalesOrdersRoute: AppSalesOrdersRoute,
  AppSettingsBranchesRoute: AppSettingsBranchesRoute,
  AppSettingsCostCentersRoute: AppSettingsCostCentersRoute,
  AppSettingsDepartmentsRoute: AppSettingsDepartmentsRoute,
  AppSettingsFiscalPeriodsRoute: AppSettingsFiscalPeriodsRoute,
  AppSettingsProjectsRoute: AppSettingsProjectsRoute,
  AppSuppliersIdRoute: AppSuppliersIdRoute,
  AppSuppliersGroupsRoute: AppSuppliersGroupsRoute,
  AppTaxGtgtRoute: AppTaxGtgtRoute,
  AppTaxTncnRoute: AppTaxTncnRoute,
  AppTaxTndnRoute: AppTaxTndnRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppCashIndexRoute: AppCashIndexRoute,
  AppCoaIndexRoute: AppCoaIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppEinvoicesIndexRoute: AppEinvoicesIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppPayablesIndexRoute: AppPayablesIndexRoute,
  AppPayrollIndexRoute: AppPayrollIndexRoute,
  AppPurchasesIndexRoute: AppPurchasesIndexRoute,
  AppReceiptsIndexRoute: AppReceiptsIndexRoute,
  AppReceivablesIndexRoute: AppReceivablesIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSalesDashboardIndexRoute: AppSalesDashboardIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
  AppTaxIndexRoute: AppTaxIndexRoute,
  AppAssetsIdCardRoute: AppAssetsIdCardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
