/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppJournalRouteImport } from './routes/_app/journal'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppBankRouteImport } from './routes/_app/bank'
import { Route as AppAssetsRouteImport } from './routes/_app/assets'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppTaxIndexRouteImport } from './routes/_app/tax/index'
import { Route as AppSuppliersIndexRouteImport } from './routes/_app/suppliers/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSalesIndexRouteImport } from './routes/_app/sales/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppReceivablesIndexRouteImport } from './routes/_app/receivables/index'
import { Route as AppPayrollIndexRouteImport } from './routes/_app/payroll/index'
import { Route as AppPayablesIndexRouteImport } from './routes/_app/payables/index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppCoaIndexRouteImport } from './routes/_app/coa/index'
import { Route as AppCashIndexRouteImport } from './routes/_app/cash/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppSuppliersIdRouteImport } from './routes/_app/suppliers/$id'
import { Route as AppSalesIdRouteImport } from './routes/_app/sales/$id'
import { Route as AppReportsLedgersRouteImport } from './routes/_app/reports/ledgers'
import { Route as AppPayrollIdRouteImport } from './routes/_app/payroll/$id'
import { Route as AppInvoicesIdRouteImport } from './routes/_app/invoices/$id'
import { Route as AppAdminPeriodsRouteImport } from './routes/_app/admin/periods'
import { Route as AppAdminMembersRouteImport } from './routes/_app/admin/members'
import { Route as AppAdminBackupRouteImport } from './routes/_app/admin/backup'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxIndexRoute = AppTaxIndexRouteImport.update({
  id: '/tax/',
  path: '/tax/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppReceivablesIndexRoute = AppReceivablesIndexRouteImport.update({
  id: '/receivables/',
  path: '/receivables/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollIndexRoute = AppPayrollIndexRouteImport.update({
  id: '/payroll/',
  path: '/payroll/',
  getParentRoute: () => AppRoute,
} as any)
const AppPayablesIndexRoute = AppPayablesIndexRouteImport.update({
  id: '/payables/',
  path: '/payables/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoaIndexRoute = AppCoaIndexRouteImport.update({
  id: '/coa/',
  path: '/coa/',
  getParentRoute: () => AppRoute,
} as any)
const AppCashIndexRoute = AppCashIndexRouteImport.update({
  id: '/cash/',
  path: '/cash/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppSuppliersIdRoute = AppSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIdRoute = AppSalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsLedgersRoute = AppReportsLedgersRouteImport.update({
  id: '/reports/ledgers',
  path: '/reports/ledgers',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollIdRoute = AppPayrollIdRouteImport.update({
  id: '/payroll/$id',
  path: '/payroll/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPeriodsRoute = AppAdminPeriodsRouteImport.update({
  id: '/periods',
  path: '/periods',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMembersRoute = AppAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBackupRoute = AppAdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/assets': typeof AppAssetsRoute
  '/bank': typeof AppBankRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/journal': typeof AppJournalRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/backup': typeof AppAdminBackupRoute
  '/admin/members': typeof AppAdminMembersRoute
  '/admin/periods': typeof AppAdminPeriodsRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/payroll/$id': typeof AppPayrollIdRoute
  '/reports/ledgers': typeof AppReportsLedgersRoute
  '/sales/$id': typeof AppSalesIdRoute
  '/suppliers/$id': typeof AppSuppliersIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/cash/': typeof AppCashIndexRoute
  '/coa/': typeof AppCoaIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/payables/': typeof AppPayablesIndexRoute
  '/payroll/': typeof AppPayrollIndexRoute
  '/receivables/': typeof AppReceivablesIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/suppliers/': typeof AppSuppliersIndexRoute
  '/tax/': typeof AppTaxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assets': typeof AppAssetsRoute
  '/bank': typeof AppBankRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/journal': typeof AppJournalRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/backup': typeof AppAdminBackupRoute
  '/admin/members': typeof AppAdminMembersRoute
  '/admin/periods': typeof AppAdminPeriodsRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/payroll/$id': typeof AppPayrollIdRoute
  '/reports/ledgers': typeof AppReportsLedgersRoute
  '/sales/$id': typeof AppSalesIdRoute
  '/suppliers/$id': typeof AppSuppliersIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/cash': typeof AppCashIndexRoute
  '/coa': typeof AppCoaIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/payables': typeof AppPayablesIndexRoute
  '/payroll': typeof AppPayrollIndexRoute
  '/receivables': typeof AppReceivablesIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/suppliers': typeof AppSuppliersIndexRoute
  '/tax': typeof AppTaxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/assets': typeof AppAssetsRoute
  '/_app/bank': typeof AppBankRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/backup': typeof AppAdminBackupRoute
  '/_app/admin/members': typeof AppAdminMembersRoute
  '/_app/admin/periods': typeof AppAdminPeriodsRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/payroll/$id': typeof AppPayrollIdRoute
  '/_app/reports/ledgers': typeof AppReportsLedgersRoute
  '/_app/sales/$id': typeof AppSalesIdRoute
  '/_app/suppliers/$id': typeof AppSuppliersIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/cash/': typeof AppCashIndexRoute
  '/_app/coa/': typeof AppCoaIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/payables/': typeof AppPayablesIndexRoute
  '/_app/payroll/': typeof AppPayrollIndexRoute
  '/_app/receivables/': typeof AppReceivablesIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/suppliers/': typeof AppSuppliersIndexRoute
  '/_app/tax/': typeof AppTaxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/assets'
    | '/bank'
    | '/chat'
    | '/dashboard'
    | '/journal'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/members'
    | '/admin/periods'
    | '/invoices/$id'
    | '/payroll/$id'
    | '/reports/ledgers'
    | '/sales/$id'
    | '/suppliers/$id'
    | '/admin/'
    | '/cash/'
    | '/coa/'
    | '/inventory/'
    | '/invoices/'
    | '/payables/'
    | '/payroll/'
    | '/receivables/'
    | '/reports/'
    | '/sales/'
    | '/settings/'
    | '/suppliers/'
    | '/tax/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/assets'
    | '/bank'
    | '/chat'
    | '/dashboard'
    | '/journal'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/members'
    | '/admin/periods'
    | '/invoices/$id'
    | '/payroll/$id'
    | '/reports/ledgers'
    | '/sales/$id'
    | '/suppliers/$id'
    | '/admin'
    | '/cash'
    | '/coa'
    | '/inventory'
    | '/invoices'
    | '/payables'
    | '/payroll'
    | '/receivables'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/tax'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/assets'
    | '/_app/bank'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/journal'
    | '/_app/admin/audit'
    | '/_app/admin/backup'
    | '/_app/admin/members'
    | '/_app/admin/periods'
    | '/_app/invoices/$id'
    | '/_app/payroll/$id'
    | '/_app/reports/ledgers'
    | '/_app/sales/$id'
    | '/_app/suppliers/$id'
    | '/_app/admin/'
    | '/_app/cash/'
    | '/_app/coa/'
    | '/_app/inventory/'
    | '/_app/invoices/'
    | '/_app/payables/'
    | '/_app/payroll/'
    | '/_app/receivables/'
    | '/_app/reports/'
    | '/_app/sales/'
    | '/_app/settings/'
    | '/_app/suppliers/'
    | '/_app/tax/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank': {
      id: '/_app/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tax/': {
      id: '/_app/tax/'
      path: '/tax'
      fullPath: '/tax/'
      preLoaderRoute: typeof AppTaxIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers/': {
      id: '/_app/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receivables/': {
      id: '/_app/receivables/'
      path: '/receivables'
      fullPath: '/receivables/'
      preLoaderRoute: typeof AppReceivablesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/': {
      id: '/_app/payroll/'
      path: '/payroll'
      fullPath: '/payroll/'
      preLoaderRoute: typeof AppPayrollIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payables/': {
      id: '/_app/payables/'
      path: '/payables'
      fullPath: '/payables/'
      preLoaderRoute: typeof AppPayablesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coa/': {
      id: '/_app/coa/'
      path: '/coa'
      fullPath: '/coa/'
      preLoaderRoute: typeof AppCoaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cash/': {
      id: '/_app/cash/'
      path: '/cash'
      fullPath: '/cash/'
      preLoaderRoute: typeof AppCashIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/suppliers/$id': {
      id: '/_app/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof AppSuppliersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/$id': {
      id: '/_app/sales/$id'
      path: '/sales/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof AppSalesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/ledgers': {
      id: '/_app/reports/ledgers'
      path: '/reports/ledgers'
      fullPath: '/reports/ledgers'
      preLoaderRoute: typeof AppReportsLedgersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll/$id': {
      id: '/_app/payroll/$id'
      path: '/payroll/$id'
      fullPath: '/payroll/$id'
      preLoaderRoute: typeof AppPayrollIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/periods': {
      id: '/_app/admin/periods'
      path: '/periods'
      fullPath: '/admin/periods'
      preLoaderRoute: typeof AppAdminPeriodsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/members': {
      id: '/_app/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AppAdminMembersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/backup': {
      id: '/_app/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AppAdminBackupRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminBackupRoute: typeof AppAdminBackupRoute
  AppAdminMembersRoute: typeof AppAdminMembersRoute
  AppAdminPeriodsRoute: typeof AppAdminPeriodsRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminBackupRoute: AppAdminBackupRoute,
  AppAdminMembersRoute: AppAdminMembersRoute,
  AppAdminPeriodsRoute: AppAdminPeriodsRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAssetsRoute: typeof AppAssetsRoute
  AppBankRoute: typeof AppBankRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppJournalRoute: typeof AppJournalRoute
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppPayrollIdRoute: typeof AppPayrollIdRoute
  AppReportsLedgersRoute: typeof AppReportsLedgersRoute
  AppSalesIdRoute: typeof AppSalesIdRoute
  AppSuppliersIdRoute: typeof AppSuppliersIdRoute
  AppCashIndexRoute: typeof AppCashIndexRoute
  AppCoaIndexRoute: typeof AppCoaIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppPayablesIndexRoute: typeof AppPayablesIndexRoute
  AppPayrollIndexRoute: typeof AppPayrollIndexRoute
  AppReceivablesIndexRoute: typeof AppReceivablesIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
  AppTaxIndexRoute: typeof AppTaxIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAssetsRoute: AppAssetsRoute,
  AppBankRoute: AppBankRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppJournalRoute: AppJournalRoute,
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppPayrollIdRoute: AppPayrollIdRoute,
  AppReportsLedgersRoute: AppReportsLedgersRoute,
  AppSalesIdRoute: AppSalesIdRoute,
  AppSuppliersIdRoute: AppSuppliersIdRoute,
  AppCashIndexRoute: AppCashIndexRoute,
  AppCoaIndexRoute: AppCoaIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppPayablesIndexRoute: AppPayablesIndexRoute,
  AppPayrollIndexRoute: AppPayrollIndexRoute,
  AppReceivablesIndexRoute: AppReceivablesIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
  AppTaxIndexRoute: AppTaxIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
