ALTER TABLE public.chart_of_accounts
  ADD COLUMN IF NOT EXISTS level smallint,
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;

ALTER TABLE public.chart_of_accounts DROP CONSTRAINT IF EXISTS chart_of_accounts_type_check;
ALTER TABLE public.chart_of_accounts ADD CONSTRAINT chart_of_accounts_type_check
  CHECK (type IN ('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE','RESULT','OTHER'));

INSERT INTO public.chart_of_accounts (code, name, parent_code, type, level) VALUES
  ('111', 'Tiền mặt', NULL, 'ASSET', 1),
  ('112', 'Tiền gửi không kỳ hạn', NULL, 'ASSET', 1),
  ('113', 'Tiền đang chuyển', NULL, 'ASSET', 1),
  ('121', 'Chứng khoán kinh doanh', NULL, 'ASSET', 1),
  ('128', 'Đầu tư nắm giữ đến ngày đáo hạn', NULL, 'ASSET', 1),
  ('1281', 'Tiền gửi có kỳ hạn', '128', 'ASSET', 2),
  ('1282', 'Trái phiếu', '128', 'ASSET', 2),
  ('1283', 'Cho vay', '128', 'ASSET', 2),
  ('1288', 'Các khoản đầu tư khác nắm giữ đến ngày đáo hạn', '128', 'ASSET', 2),
  ('131', 'Phải thu của khách hàng', NULL, 'ASSET', 1),
  ('133', 'Thuế GTGT được khấu trừ', NULL, 'ASSET', 1),
  ('1331', 'Thuế GTGT được khấu trừ của hàng hóa, dịch vụ', '133', 'ASSET', 2),
  ('1332', 'Thuế GTGT được khấu trừ của TSCĐ', '133', 'ASSET', 2),
  ('136', 'Phải thu nội bộ', NULL, 'ASSET', 1),
  ('1361', 'Vốn kinh doanh ở đơn vị trực thuộc', '136', 'ASSET', 2),
  ('1362', 'Phải thu nội bộ về chênh lệch tỷ giá', '136', 'ASSET', 2),
  ('1363', 'Phải thu nội bộ về chi phí đi vay đủ điều kiện được vốn hoá', '136', 'ASSET', 2),
  ('1368', 'Phải thu nội bộ khác', '136', 'ASSET', 2),
  ('138', 'Phải thu khác', NULL, 'ASSET', 1),
  ('1381', 'Tài sản thiếu chờ xử lý', '138', 'ASSET', 2),
  ('1383', 'Thuế TTĐB của hàng nhập khẩu', '138', 'ASSET', 2),
  ('1388', 'Phải thu khác', '138', 'ASSET', 2),
  ('141', 'Tạm ứng', NULL, 'ASSET', 1),
  ('151', 'Hàng mua đang đi đường', NULL, 'ASSET', 1),
  ('152', 'Nguyên liệu, vật liệu', NULL, 'ASSET', 1),
  ('153', 'Công cụ, dụng cụ', NULL, 'ASSET', 1),
  ('154', 'Chi phí sản xuất, kinh doanh dở dang', NULL, 'ASSET', 1),
  ('155', 'Sản phẩm', NULL, 'ASSET', 1),
  ('156', 'Hàng hóa', NULL, 'ASSET', 1),
  ('157', 'Hàng gửi đi bán', NULL, 'ASSET', 1),
  ('158', 'Nguyên liệu, vật tư tại kho bảo thuế', NULL, 'ASSET', 1),
  ('171', 'Giao dịch mua, bán lại trái phiếu chính phủ', NULL, 'ASSET', 1),
  ('211', 'Tài sản cố định hữu hình', NULL, 'ASSET', 1),
  ('212', 'Tài sản cố định thuê tài chính', NULL, 'ASSET', 1),
  ('213', 'Tài sản cố định vô hình', NULL, 'ASSET', 1),
  ('214', 'Hao mòn tài sản cố định', NULL, 'ASSET', 1),
  ('2141', 'Hao mòn TSCĐ hữu hình', '214', 'ASSET', 2),
  ('2142', 'Hao mòn TSCĐ thuê tài chính', '214', 'ASSET', 2),
  ('2143', 'Hao mòn TSCĐ vô hình', '214', 'ASSET', 2),
  ('2147', 'Hao mòn BĐSĐT', '214', 'ASSET', 2),
  ('215', 'Tài sản sinh học', NULL, 'ASSET', 1),
  ('2151', 'Súc vật nuôi cho sản phẩm định kỳ', '215', 'ASSET', 2),
  ('2152', 'Súc vật nuôi lấy sản phẩm một lần', '215', 'ASSET', 2),
  ('2153', 'Cây trồng theo mùa vụ hoặc lấy sản phẩm một lần', '215', 'ASSET', 2),
  ('217', 'Bất động sản đầu tư', NULL, 'ASSET', 1),
  ('221', 'Đầu tư vào công ty con', NULL, 'ASSET', 1),
  ('222', 'Đầu tư vào công ty liên doanh, liên kết', NULL, 'ASSET', 1),
  ('228', 'Đầu tư khác', NULL, 'ASSET', 1),
  ('2281', 'Đầu tư góp vốn vào đơn vị khác', '228', 'ASSET', 2),
  ('2288', 'Đầu tư khác', '228', 'ASSET', 2),
  ('229', 'Dự phòng tổn thất tài sản', NULL, 'ASSET', 1),
  ('2291', 'Dự phòng giảm giá chứng khoán kinh doanh', '229', 'ASSET', 2),
  ('2292', 'Dự phòng tổn thất đầu tư vào đơn vị khác', '229', 'ASSET', 2),
  ('2293', 'Dự phòng phải thu khó đòi', '229', 'ASSET', 2),
  ('2294', 'Dự phòng giảm giá hàng tồn kho', '229', 'ASSET', 2),
  ('2295', 'Dự phòng tổn thất tài sản sinh học', '229', 'ASSET', 2),
  ('241', 'Xây dựng cơ bản dở dang', NULL, 'ASSET', 1),
  ('2411', 'Mua sắm TSCĐ', '241', 'ASSET', 2),
  ('2412', 'Xây dựng cơ bản', '241', 'ASSET', 2),
  ('2413', 'Sửa chữa, bảo dưỡng định kỳ TSCĐ', '241', 'ASSET', 2),
  ('2414', 'Nâng cấp, cải tạo TSCĐ', '241', 'ASSET', 2),
  ('242', 'Chi phí chờ phân bổ', NULL, 'ASSET', 1),
  ('243', 'Tài sản thuế thu nhập hoãn lại', NULL, 'ASSET', 1),
  ('244', 'Ký quỹ, ký cược', NULL, 'ASSET', 1),
  ('331', 'Phải trả cho người bán', NULL, 'LIABILITY', 1),
  ('332', 'Phải trả cổ tức, lợi nhuận', NULL, 'LIABILITY', 1),
  ('333', 'Thuế và các khoản phải nộp Nhà nước', NULL, 'LIABILITY', 1),
  ('3331', 'Thuế giá trị gia tăng phải nộp', '333', 'LIABILITY', 2),
  ('3332', 'Thuế tiêu thụ đặc biệt', '333', 'LIABILITY', 2),
  ('3333', 'Thuế xuất, nhập khẩu', '333', 'LIABILITY', 2),
  ('3334', 'Thuế thu nhập doanh nghiệp', '333', 'LIABILITY', 2),
  ('3335', 'Thuế thu nhập cá nhân', '333', 'LIABILITY', 2),
  ('3336', 'Thuế tài nguyên', '333', 'LIABILITY', 2),
  ('3337', 'Thuế nhà đất, tiền thuê đất', '333', 'LIABILITY', 2),
  ('3338', 'Thuế bảo vệ môi trường và các loại thuế khác', '333', 'LIABILITY', 2),
  ('3339', 'Phí, lệ phí và các khoản phải nộp khác', '333', 'LIABILITY', 2),
  ('334', 'Phải trả người lao động', NULL, 'LIABILITY', 1),
  ('335', 'Chi phí phải trả', NULL, 'LIABILITY', 1),
  ('336', 'Phải trả nội bộ', NULL, 'LIABILITY', 1),
  ('3361', 'Phải trả nội bộ về vốn kinh doanh', '336', 'LIABILITY', 2),
  ('3362', 'Phải trả nội bộ về chênh lệch tỷ giá', '336', 'LIABILITY', 2),
  ('3363', 'Phải trả nội bộ về chi phí đi vay đủ điều kiện được vốn hoá', '336', 'LIABILITY', 2),
  ('3368', 'Phải trả nội bộ khác', '336', 'LIABILITY', 2),
  ('337', 'Thanh toán theo tiến độ hợp đồng xây dựng', NULL, 'LIABILITY', 1),
  ('338', 'Phải trả, phải nộp khác', NULL, 'LIABILITY', 1),
  ('3381', 'Tài sản thừa chờ giải quyết', '338', 'LIABILITY', 2),
  ('3382', 'Kinh phí công đoàn', '338', 'LIABILITY', 2),
  ('3383', 'Bảo hiểm xã hội', '338', 'LIABILITY', 2),
  ('3384', 'Bảo hiểm y tế', '338', 'LIABILITY', 2),
  ('3386', 'Bảo hiểm thất nghiệp', '338', 'LIABILITY', 2),
  ('3387', 'Doanh thu chờ phân bổ', '338', 'LIABILITY', 2),
  ('3388', 'Phải trả, phải nộp khác', '338', 'LIABILITY', 2),
  ('341', 'Vay và nợ thuê tài chính', NULL, 'LIABILITY', 1),
  ('3411', 'Các khoản đi vay', '341', 'LIABILITY', 2),
  ('3412', 'Nợ thuê tài chính', '341', 'LIABILITY', 2),
  ('343', 'Trái phiếu phát hành', NULL, 'LIABILITY', 1),
  ('3431', 'Trái phiếu thường', '343', 'LIABILITY', 2),
  ('3432', 'Trái phiếu chuyển đổi', '343', 'LIABILITY', 2),
  ('344', 'Nhận ký quỹ, ký cược', NULL, 'LIABILITY', 1),
  ('347', 'Thuế thu nhập hoãn lại phải trả', NULL, 'LIABILITY', 1),
  ('352', 'Dự phòng phải trả', NULL, 'LIABILITY', 1),
  ('3521', 'Dự phòng bảo hành sản phẩm, hàng hóa', '352', 'LIABILITY', 2),
  ('3522', 'Dự phòng bảo hành công trình xây dựng', '352', 'LIABILITY', 2),
  ('3523', 'Dự phòng tái cơ cấu doanh nghiệp', '352', 'LIABILITY', 2),
  ('3525', 'Dự phòng phải trả khác', '352', 'LIABILITY', 2),
  ('353', 'Quỹ khen thưởng, phúc lợi', NULL, 'LIABILITY', 1),
  ('3531', 'Quỹ khen thưởng', '353', 'LIABILITY', 2),
  ('356', 'Quỹ phát triển khoa học và công nghệ', NULL, 'LIABILITY', 1),
  ('3561', 'Quỹ phát triển khoa học và công nghệ', '356', 'LIABILITY', 2),
  ('357', 'Quỹ bình ổn giá', NULL, 'LIABILITY', 1),
  ('411', 'Vốn đầu tư của chủ sở hữu', NULL, 'EQUITY', 1),
  ('4111', 'Vốn góp của chủ sở hữu', '411', 'EQUITY', 2),
  ('412', 'Chênh lệch đánh giá lại tài sản', NULL, 'EQUITY', 1),
  ('413', 'Chênh lệch tỷ giá hối đoái', NULL, 'EQUITY', 1),
  ('414', 'Quỹ đầu tư phát triển', NULL, 'EQUITY', 1),
  ('418', 'Các quỹ khác thuộc vốn chủ sở hữu', NULL, 'EQUITY', 1),
  ('419', 'Cổ phiếu mua lại của chính mình', NULL, 'EQUITY', 1),
  ('421', 'Lợi nhuận sau thuế chưa phân phối', NULL, 'EQUITY', 1),
  ('4211', 'Lợi nhuận sau thuế chưa phân phối lũy kế đến cuối năm trước', '421', 'EQUITY', 2),
  ('4212', 'Lợi nhuận sau thuế chưa phân phối năm nay', '421', 'EQUITY', 2),
  ('511', 'Doanh thu bán hàng và cung cấp dịch vụ', NULL, 'REVENUE', 1),
  ('515', 'Doanh thu hoạt động tài chính', NULL, 'REVENUE', 1),
  ('521', 'Các khoản giảm trừ doanh thu', NULL, 'REVENUE', 1),
  ('621', 'Chi phí nguyên liệu, vật liệu trực tiếp', NULL, 'EXPENSE', 1),
  ('622', 'Chi phí nhân công trực tiếp', NULL, 'EXPENSE', 1),
  ('623', 'Chi phí sử dụng máy thi công', NULL, 'EXPENSE', 1),
  ('6231', 'Chi phí nhân công', '623', 'EXPENSE', 2),
  ('6232', 'Chi phí vật liệu', '623', 'EXPENSE', 2),
  ('6233', 'Chi phí dụng cụ sản xuất', '623', 'EXPENSE', 2),
  ('6234', 'Chi phí khấu hao máy thi công', '623', 'EXPENSE', 2),
  ('6237', 'Chi phí dịch vụ mua ngoài', '623', 'EXPENSE', 2),
  ('6238', 'Chi phí bằng tiền khác', '623', 'EXPENSE', 2),
  ('627', 'Chi phí sản xuất chung', NULL, 'EXPENSE', 1),
  ('6271', 'Chi phí nhân viên phân xưởng', '627', 'EXPENSE', 2),
  ('6272', 'Chi phí vật liệu', '627', 'EXPENSE', 2),
  ('6273', 'Chi phí dụng cụ sản xuất', '627', 'EXPENSE', 2),
  ('6274', 'Chi phí khấu hao TSCĐ', '627', 'EXPENSE', 2),
  ('6275', 'Thuế, phí, lệ phí', '627', 'EXPENSE', 2),
  ('6277', 'Chi phí dịch vụ mua ngoài', '627', 'EXPENSE', 2),
  ('6278', 'Chi phí bằng tiền khác', '627', 'EXPENSE', 2),
  ('632', 'Giá vốn hàng bán', NULL, 'EXPENSE', 1),
  ('635', 'Chi phí tài chính', NULL, 'EXPENSE', 1),
  ('641', 'Chi phí bán hàng', NULL, 'EXPENSE', 1),
  ('6411', 'Chi phí nhân viên', '641', 'EXPENSE', 2),
  ('6412', 'Chi phí vật liệu, bao bì', '641', 'EXPENSE', 2),
  ('6413', 'Chi phí dụng cụ, đồ dùng', '641', 'EXPENSE', 2),
  ('6414', 'Chi phí khấu hao TSCĐ', '641', 'EXPENSE', 2),
  ('6415', 'Chi phí bảo hành', '641', 'EXPENSE', 2),
  ('6417', 'Chi phí dịch vụ mua ngoài', '641', 'EXPENSE', 2),
  ('6418', 'Chi phí bằng tiền khác', '641', 'EXPENSE', 2),
  ('642', 'Chi phí quản lý doanh nghiệp', NULL, 'EXPENSE', 1),
  ('6421', 'Chi phí nhân viên quản lý', '642', 'EXPENSE', 2),
  ('6422', 'Chi phí vật liệu quản lý', '642', 'EXPENSE', 2),
  ('6423', 'Chi phí đồ dùng văn phòng', '642', 'EXPENSE', 2),
  ('6424', 'Chi phí khấu hao TSCĐ', '642', 'EXPENSE', 2),
  ('6425', 'Thuế, phí và lệ phí', '642', 'EXPENSE', 2),
  ('6426', 'Chi phí dự phòng', '642', 'EXPENSE', 2),
  ('6427', 'Chi phí dịch vụ mua ngoài', '642', 'EXPENSE', 2),
  ('6428', 'Chi phí bằng tiền khác', '642', 'EXPENSE', 2),
  ('711', 'Thu nhập khác', NULL, 'REVENUE', 1),
  ('811', 'Chi phí khác', NULL, 'EXPENSE', 1),
  ('821', 'Chi phí thuế thu nhập doanh nghiệp', NULL, 'EXPENSE', 1),
  ('8211', 'Chi phí thuế TNDN hiện hành', '821', 'EXPENSE', 2),
  ('8212', 'Chi phí thuế TNDN hoãn lại', '821', 'EXPENSE', 2),
  ('911', 'Xác định kết quả kinh doanh', NULL, 'RESULT', 1)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  parent_code = EXCLUDED.parent_code,
  type = EXCLUDED.type,
  level = EXCLUDED.level;